language: python

python:
  - "3.6"

cache: pip

install:
  - pip install tox-travis
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -r requirements_testing.txt

script:
  - tox

after_success:
  - coveralls
